version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: promptforge_postgres
    restart: always
    environment:
      POSTGRES_USER: promptforge
      POSTGRES_PASSWORD: promptforge123
      POSTGRES_DB: promptforge_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: promptforge_backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DATABASE_URL=postgresql://promptforge:promptforge123@postgres:5432/promptforge_db?schema=public
      - JWT_SECRET=change_this_to_a_secure_secret_at_least_32_chars
      # - NEXT_PUBLIC_API_URL=http://localhost:4000/api
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: promptforge_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@promptforge.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
